### ISSUE TITLE
npm links to wrong repo

### ISSUE THREAD

**Issue by earthiverse** [gian788/i18next-node-mongodb-backend#1]
NPM links to https://github.com/gian788/docsgen/ instead of https://github.com/gian788/i18next-node-mongodb-backend

See: https://www.npmjs.com/package/i18next-node-mongodb-backend

**Comment by earthiverse** [comment]
Also, unrelated to above, but the readme still mentions `var Backend = require('i18next-node-fs-backend');` instead of `var Backend = require('i18next-node-mongodb-backend');`

**Comment by gian788** [comment]
Thanks @earthiverse! 
I fixed all the links.
